# disable in production:  
local_backend: true
# command to run a local Decap instance: npx-decap-server

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
locale: cs

media_folder: "/public/upload"
public_folder: "/"

site_url: https://lovely-crepe-8a1468.netlify.app

# --- Reusable components ---
basic_info_box: &basic_info_box
  - { label: "Nadpis", name: "title", widget: "string" }
  - { label: "Popis", name: "description", widget: "markdown" }

photo_item: &photo_item
  - { label: "Obrázek", name: "image", widget: "image", required: true }
  - { label: "Popis obrázku (alt)", name: "alt", widget: "string", required: false }

photo_item-1-1: &photo_item-1-1
  - { label: "Obrázek (1x1)", name: "image", widget: "image", required: true }
  - { label: "Popis obrázku (alt)", name: "alt", widget: "string", required: false  }

# our-work komponenta: Reference s galerií obrázků
our_work_component: &our_work_component
  - { label: "Nadpis reference", name: "reference_heading", widget: "string" }
  - label: "Galerie obrázků"
    name: "gallery"
    widget: "list"
    fields:
      - { label: "Obrázek", name: "image", widget: "image", required: true }
      - { label: "Popis obrázku (alt)", name: "alt", widget: "string" }

# employee komponenta: jméno a email
employee: &employee
  - { label: "Jméno", name: "name", widget: "string" }
  - { label: "Email", name: "email", widget: "string" }

collections:
  - name: "pages"
    label: "Stránky"
    format: "json" 
    extension: "json" 
    files:

      - file: "content/uvod.json"
        label: "Úvod"
        name: "uvod"
        media_folder: "/public/upload/uvod"
        public_folder: "/upload/uvod/" 
        fields:
          - { label: "Úvodní obrázek", name: "cover", widget: "object", fields: *photo_item }
          - { label: "Uvítací text", name: "supplement", widget: "markdown" }
          - { label: "List fotografií", name: "photoList", widget: "list", fields: *photo_item-1-1 }

      - file: "content/kdo-jsme.json"
        label: "Kdo jsme"
        name: "kdo-jsme"
        media_folder: "/public/upload/kdo-jsme"
        public_folder: "/upload/kdo-jsme/" 
        fields:
          - { label: "Úvodní obrázek", name: "cover", widget: "object", fields: *photo_item }
          - { label: "Úvodní popis", name: "description", widget: "markdown" }
          - { label: "Jednotlivé body", name: "basic_info_boxes", widget: "list", fields: *basic_info_box }

      - file: "content/co-nabizime.json"
        label: "Co nabízíme"
        name: "co-nabizime"
        media_folder: "/public/upload/co-nabizime"
        public_folder: "/upload/co-nabizime/" 
        fields:
          - { label: "Úvodní obrázek", name: "cover", widget: "object", fields: *photo_item }
          - { label: "Úvodní popis", name: "description", widget: "markdown"}
          - { label: "Jednotlivé body", name: "basic_info_boxes", widget: "list", fields: *basic_info_box }

      - file: "content/nase-prace.md"
        label: "Naše práce"
        name: "nase-prace"
        fields:
          - label: "Our Work"
            name: "our_work"
            widget: "list"
            fields: *our_work_component

      - file: "content/kontakty.json"
        label: "Kontakty"
        name: "kontakty"
        fields:
          - { label: "GPS souřadnice středu mapy", name: "gps", widget: "string" }
          - { label: "Kontaktní údaje", name: "description", widget: "markdown" }
          - label: "Zaměstnanci"
            name: "employees"
            widget: "list"
            fields: *employee

      - file: "content/ke-stazeni.json"
        label: "Ke stažení"
        name: "ke-stazeni"
        media_folder: "/public/upload/ke-stazeni"
        public_folder: "/upload/ke-stazeni/"
        fields:
          - { label: "Úvodní obrázek", name: "cover", widget: "object", fields: *photo_item }
          - label: "Sekce ke stažení"
            name: "download_sections"
            widget: "list"
            fields:
              - { label: "Nadpis sekce", name: "section_title", widget: "string" }
              - label: "Soubory ke stažení"
                name: "files"
                widget: "list"
                fields:
                  - { label: "Název souboru", name: "title", widget: "string" }
                  - { label: "Soubor", name: "file", widget: "file" }
